### PR TITLE
fixed main files in bower.json

### PR DESCRIPTION
**Pull request by fmquaglia**
@mahdaen I tried installing the module with bower to find out that the ```main``` property in ```bower.json``` has a wrong value. (see [here](https://github.com/cobolab/ionicon/blob/master/bower.json#L8))

Therefore the ```wiredep:js``` and ```wiredep:css``` task of the ```grunt-wiredep```module is not able to include properly the source files.

I fixed the ```main```property to include the correct files. (see [here](https://github.com/circleback/ionicon/blob/fix_bower_main/bower.json#L8-L10))

### CODE REVIEW

**Comment by mahdaen** [comment]
Hey @fmquaglia, thanks for the fixes. Will merge it ;)

**Comment by fmquaglia** [comment]
@mahdaen I'm glad to help. 😄

**Comment by fmquaglia** [comment]
@mahdaen by the way, if you could publish a new release we will be able to pick up the update using bower.

Thanks, and sorry for the inconveniences.

**Comment by mahdaen** [comment]
sure, i just published new release. try to update ;)

**Comment by fmquaglia** [comment]
That worked like a charm. Thanks for the prompt action @mahdaen 👍

**Comment by mahdaen** [comment]
You're welcome and thanks for helping @fmquaglia ;)

**Pull request merged**
